language: node_js
node_js:
  - "18"
dist: "focal"

cache:
  directories:
    - webapp/node_modules
    - api-provider/node_modules

jobs:
  include:
    - name: "Frontend Tests"
      before_script:
        - cd webapp
        - npm install
      script:
        - npm test run

    - name: "Backend Tests"
      before_script:
        - cd api-provider
        - npm install
        # - apt-install tree && tree -fa | grep -v "node_modules"
        - npx prisma generate --schema "$PWD/src/prisma/schema.prisma" # --schema "$PWD/api-provider/src/prisma/schema.prisma"
      script:
        - npm test

notifications:
  email:
    on_success: change
    on_failure: always
